package com.example.samsungzh

object Vocabulary {
    val words = listOf(
        WordEntry("你好", "ni hao", "hello"),
        WordEntry("謝謝", "xie xie", "thank you"),
        WordEntry("學習", "xue xi", "to study"),
        WordEntry("中文", "zhong wen", "Chinese language"),
        WordEntry("朋友", "peng you", "friend"),
        WordEntry("今天", "jin tian", "today"),
        WordEntry("明天", "ming tian", "tomorrow"),
        WordEntry("昨天", "zuo tian", "yesterday"),
        WordEntry("喜歡", "xi huan", "to like"),
        WordEntry("知道", "zhi dao", "to know"),
        WordEntry("可以", "ke yi", "can; may"),
        WordEntry("因為", "yin wei", "because"),
        WordEntry("所以", "suo yi", "therefore"),
        WordEntry("時間", "shi jian", "time"),
        WordEntry("工作", "gong zuo", "work"),
        WordEntry("學校", "xue xiao", "school"),
        WordEntry("老師", "lao shi", "teacher"),
        WordEntry("學生", "xue sheng", "student"),
        WordEntry("東西", "dong xi", "thing"),
        WordEntry("天氣", "tian qi", "weather"),
        WordEntry("吃飯", "chi fan", "to eat"),
        WordEntry("喝水", "he shui", "to drink water"),
        WordEntry("睡覺", "shui jiao", "to sleep"),
        WordEntry("看書", "kan shu", "to read"),
        WordEntry("聽見", "ting jian", "to hear"),
        WordEntry("說話", "shuo hua", "to speak"),
        WordEntry("漂亮", "piao liang", "beautiful"),
        WordEntry("高興", "gao xing", "happy"),
        WordEntry("重要", "zhong yao", "important"),
        WordEntry("問題", "wen ti", "question; problem"),
        WordEntry("幫忙", "bang mang", "to help"),
        WordEntry("手機", "shou ji", "mobile phone"),
        WordEntry("電腦", "dian nao", "computer"),
        WordEntry("城市", "cheng shi", "city"),
        WordEntry("國家", "guo jia", "country"),
        WordEntry("家人", "jia ren", "family"),
        WordEntry("早上", "zao shang", "morning"),
        WordEntry("晚上", "wan shang", "evening"),
        WordEntry("現在", "xian zai", "now"),
        WordEntry("以後", "yi hou", "after; later"),
        WordEntry("捷運", "jie yun", "MRT; metro"),
        WordEntry("公車", "gong che", "bus"),
        WordEntry("計程車", "ji cheng che", "taxi"),
        WordEntry("腳踏車", "jiao ta che", "bicycle"),
        WordEntry("機車", "ji che", "scooter"),
        WordEntry("便當", "bian dang", "boxed meal"),
        WordEntry("飲料", "yin liao", "drink"),
        WordEntry("早餐", "zao can", "breakfast"),
        WordEntry("午餐", "wu can", "lunch"),
        WordEntry("晚餐", "wan can", "dinner"),
        WordEntry("夜市", "ye shi", "night market"),
        WordEntry("便利商店", "bian li shang dian", "convenience store"),
        WordEntry("發票", "fa piao", "receipt; invoice"),
        WordEntry("悠遊卡", "you you ka", "EasyCard"),
        WordEntry("不好意思", "bu hao yi si", "excuse me; sorry"),
        WordEntry("沒關係", "mei guan xi", "it is okay"),
        WordEntry("請問", "qing wen", "may I ask"),
        WordEntry("麻煩你", "ma fan ni", "please trouble you"),
        WordEntry("沒問題", "mei wen ti", "no problem"),
        WordEntry("等一下", "deng yi xia", "wait a moment"),
        WordEntry("慢慢來", "man man lai", "take your time"),
        WordEntry("再說一次", "zai shuo yi ci", "say it again"),
        WordEntry("聽不懂", "ting bu dong", "cannot understand by listening"),
        WordEntry("看不懂", "kan bu dong", "cannot understand by reading"),
        WordEntry("怎麼說", "zen me shuo", "how do you say it"),
        WordEntry("多少錢", "duo shao qian", "how much money"),
        WordEntry("太貴了", "tai gui le", "too expensive"),
        WordEntry("便宜一點", "pian yi yi dian", "a little cheaper"),
        WordEntry("不用袋子", "bu yong dai zi", "no bag needed"),
        WordEntry("內用", "nei yong", "for here"),
        WordEntry("外帶", "wai dai", "to go"),
        WordEntry("加辣", "jia la", "add spice"),
        WordEntry("不要辣", "bu yao la", "not spicy"),
        WordEntry("少冰", "shao bing", "less ice"),
        WordEntry("半糖", "ban tang", "half sugar"),
        WordEntry("無糖", "wu tang", "no sugar"),
        WordEntry("排隊", "pai dui", "to line up"),
        WordEntry("訂位", "ding wei", "to reserve a seat"),
        WordEntry("結帳", "jie zhang", "to pay the bill"),
        WordEntry("收據", "shou ju", "receipt"),
        WordEntry("地址", "di zhi", "address"),
        WordEntry("附近", "fu jin", "nearby"),
        WordEntry("左邊", "zuo bian", "left side"),
        WordEntry("右邊", "you bian", "right side"),
        WordEntry("前面", "qian mian", "in front"),
        WordEntry("後面", "hou mian", "behind"),
        WordEntry("樓上", "lou shang", "upstairs"),
        WordEntry("樓下", "lou xia", "downstairs"),
        WordEntry("入口", "ru kou", "entrance"),
        WordEntry("出口", "chu kou", "exit"),
        WordEntry("上班", "shang ban", "to go to work"),
        WordEntry("下班", "xia ban", "to get off work"),
        WordEntry("開會", "kai hui", "to have a meeting"),
        WordEntry("安排", "an pai", "to arrange"),
        WordEntry("決定", "jue ding", "to decide"),
        WordEntry("計畫", "ji hua", "plan"),
        WordEntry("經驗", "jing yan", "experience"),
        WordEntry("機會", "ji hui", "opportunity"),
        WordEntry("習慣", "xi guan", "habit"),
        WordEntry("生活", "sheng huo", "life"),
        WordEntry("環境", "huan jing", "environment"),
        WordEntry("文化", "wen hua", "culture"),
        WordEntry("健康", "jian kang", "health"),
        WordEntry("運動", "yun dong", "exercise; sport"),
        WordEntry("旅行", "lv xing", "travel"),
        WordEntry("照片", "zhao pian", "photo"),
        WordEntry("消息", "xiao xi", "news; information"),
        WordEntry("安全", "an quan", "safe; safety"),
        WordEntry("方便", "fang bian", "convenient"),
        WordEntry("特別", "te bie", "special"),
        WordEntry("清楚", "qing chu", "clear"),
        WordEntry("需要", "xu yao", "to need"),
    )
}
